// by cipher.org.uk
import Foundation

/// Builds the Markdown review report for a pull request.
///
/// The report is written locally and never sent anywhere: Karma Pro holds no
/// write scope against any forge, so the strongest guarantee it can offer is
/// that the only copy of this text is the file the user chose to save.
///
/// Ordering reflects the review workflow: what this PR introduced comes first,
/// because that is the only section a reviewer has to act on. Inherited
/// problems follow under a collapsed heading so they inform without burying
/// the signal, and fixes are listed last because they are informational.
enum PRMarkdownReport {
    static func generate(session: PRReviewSession,
                         includePreExisting: Bool,
                         includeFixed: Bool) -> String {
        let context = session.context
        let pr = context.pr
        let repo = context.repo

        var lines: [String] = []
        lines.append("# \(pr.title)")
        lines.append("")
        lines.append("**Pull request #\(pr.number)** · \(repo.repoSlug)")
        lines.append("")
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| Author | \(pr.author) |")
        lines.append("| Branches | `\(pr.headBranch)` → `\(pr.baseBranch)` |")
        lines.append("| Head commit | `\(shortSHA(pr.headSHA))` |")
        if !pr.webURL.isEmpty {
            lines.append("| Link | \(pr.webURL) |")
        }
        lines.append("| Files changed | \(context.changedFiles.count) |")
        if let updated = pr.updatedAt {
            lines.append("| Last updated | \(isoString(updated)) |")
        }
        // The app is named "Karma Pro" and the reports say just that. The bundle
        // version is not stamped into the document: a report gets pasted into
        // review threads and read by people who have never installed the app,
        // where a version number is noise that will date the file.
        lines.append("| Generated by | Karma Pro on \(isoString(Date())) |")
        lines.append("")

        guard session.didScan else {
            lines.append("_No scan has been run for this pull request yet._")
            return lines.joined(separator: "\n")
        }

        let findings = session.findings
        let introduced = DiffAwareClassifier.introduced(findings)
        let contextual = DiffAwareClassifier.contextual(findings)
        let preExisting = DiffAwareClassifier.preExisting(findings)
        let fixed = DiffAwareClassifier.fixed(findings)

        lines.append("## Summary")
        lines.append("")
        lines.append("- **New in this pull request:** \(introduced.count)")
        lines.append("- Pre-existing, not introduced here: \(preExisting.count)")
        lines.append("- Touched by this PR, needs a user look: \(contextual.count)")
        lines.append("- Fixed by this pull request: \(fixed.count)")
        lines.append("")
        if introduced.isEmpty && contextual.isEmpty {
            lines.append("No new issues were found in the code this pull request adds or modifies.")
        }
        lines.append("")

        if !introduced.isEmpty {
            lines.append("## New in this pull request")
            lines.append("")
            lines.append(contentsOf: render(introduced))
            lines.append("")
        }

        if !contextual.isEmpty {
            lines.append("## Touched by this pull request")
            lines.append("")
            lines.append("These sit in files the PR modifies but not in changed lines, and did not appear in the base scan. Worth a look, not a verdict.")
            lines.append("")
            lines.append(contentsOf: render(contextual))
            lines.append("")
        }

        // Collapsed so the long inherited list cannot push the actionable
        // section out of view.
        if includePreExisting, !preExisting.isEmpty {
            lines.append("<details>")
            lines.append("<summary>Pre-existing issues not introduced here (\(preExisting.count))</summary>")
            lines.append("")
            lines.append(contentsOf: render(preExisting))
            lines.append("")
            lines.append("</details>")
            lines.append("")
        }

        if includeFixed, !fixed.isEmpty {
            lines.append("## Fixed by this pull request")
            lines.append("")
            lines.append(contentsOf: render(fixed))
            lines.append("")
        }

        if !context.changedFiles.isEmpty {
            lines.append("## Files changed")
            lines.append("")
            lines.append("| | Path |")
            lines.append("|---|---|")
            for file in context.changedFiles.sorted(by: { $0.path < $1.path }) {
                let path = file.kind == .renamed
                    ? "\(file.oldPath ?? "") → \(file.path)"
                    : file.path
                lines.append("| \(file.kind.badge) | `\(path)` |")
            }
            lines.append("")
        }

        lines.append("---")
        lines.append("")
        lines.append("Findings marked *new* were confirmed by the same scanner against this pull request's base commit. This report is generated locally by Karma Pro and has not been posted anywhere.")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    /// A finding as one Markdown list entry with its evidence.
    private static func render(_ items: [DiffAwareFinding]) -> [String] {
        var lines: [String] = []
        for item in items {
            let f = item.finding
            let location = "`\(relativePath(f.fileURL)):\(f.line)`"
            lines.append("- **\(f.severity.label)** · \(f.category) · \(location)")
            lines.append("  - \(f.message)")
            if !f.function.isEmpty {
                lines.append("  - In `\(f.function)`")
            }
            if let taint = f.taint, !taint.isEmpty {
                lines.append("  - Taint: \(taint)")
            } else if let path = f.taintPath, !path.isEmpty {
                lines.append("  - Taint path: \(path)")
            }
            if f.crossFile {
                lines.append("  - Source of the taint is defined in another file.")
            }
            if f.reachable {
                lines.append("  - Reachable at runtime.")
            }
            lines.append("  - Detected by: \(f.scanningSource)")
        }
        return lines
    }

    /// Repo-relative path, preferring the parent directory name when the URL
    /// carries no meaningful hierarchy of its own.
    private static func relativePath(_ url: URL) -> String {
        let path = url.path
        return path.hasPrefix("/") ? String(path.dropFirst()) : path
    }

    private static func shortSHA(_ sha: String) -> String {
        sha.isEmpty ? "unknown" : String(sha.prefix(12))
    }

    private static func isoString(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd HH:mm ZZZZZ"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        return formatter.string(from: date)
    }
}

/// App version read from the bundle.
///
/// Reports deliberately do not print this: they say "Karma Pro" and nothing
/// else. It stays here because the About window and the crash log header still
/// want the running version, and both should read it from one place rather than
/// re-deriving it.
enum KarmaVersion {
    static let current = Bundle.main.object(forInfoDictionaryKey: "CFBundleShortVersionString") as? String ?? "1.0"
}